name: podcast_demo
description: "A podcast demo project"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_riverpod: ^3.0.3
  google_fonts: ^6.3.2
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.7
  shared_preferences:
  just_audio:
  audio_session:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


flutter_native_splash:
  color: "#00B12C"
  image: assets/images/splash_jolly.png
  android_gravity: fill
  ios_content_mode: scaleAspectFill

  android_12:
    color: "#00B12C"
    image: assets/images/native_splash.png
    icon_background_color: "#00B12C"
